### ISSUE TITLE
[BUG] Minimap size not set on first load/fresh load after cache clear

### ISSUE THREAD

**Issue by ChickenDipper1** [qbcore-framework/qb-hud#170]
### Summary

The minimap will not have any size applied to it on a players first server join or if a player deletes fivem cache

### Reproduction

1. Join server for the first time, map will show as below.
![image](https://user-images.githubusercontent.com/41157940/200803410-e4705227-1f15-4714-8313-90d6f924c904.png)

2. Refresh QB-hud or leave and join server or use "Reset settings" in hud menu, the map will then be resized as below.
![image](https://user-images.githubusercontent.com/41157940/200803539-6d9cc6a0-b701-403e-a7a1-0f0395293190.png)

Using PS-hud and don't have this issue, PS-hud must be applying the default settings on first load.

This isn't related to the border or safe zone settings, this is the actual map size not being correct.

### Expected behavior

Map should be correct size on first load/join.

### Actual behavior

Map does not resize to correct size.

### Last Updated

Replaced qb-hud when testing with fresh install, same issue.

### Custom Resources

No

### Resource Rename

No

**Comment by tom-osborne** [comment]
@ChickenDipper1 are you by chance playing in windowed mode? (or anything other than fullscreen?)

**Comment by ChickenDipper1** [comment]
@tom-osborne yes while building the server, but this still happens in full screen too.

**Comment by RumDum3** [comment]
should be fixed by just adding `repeat Citizen.Wait(250) until NetworkIsPlayerActive(PlayerId())` before the minimap stuff loads

**Comment by centriukas** [comment]
> should be fixed by just adding `repeat Citizen.Wait(250) until NetworkIsPlayerActive(PlayerId())` before the minimap stuff loads

where this should go which file?

**Comment by GhzGarage** [comment]
Do we know if this issue still exists?

**Comment by CrystalTwoK** [comment]
@GhzGarage still exists and sometimes, in my case, the minimap loads attached to the left border with 0px margin.

**Comment by promiiss033** [comment]
still got this
